# Generated by Django 5.2.3 on 2025-06-30 07:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_compatibilityrules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, unique=True),
        ),
    ]
