# Generated by Django 5.2.3 on 2025-07-08 04:04

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_color_hex_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, unique=True),
        ),
        migrations.AlterField(
            model_name='compatibilityrules',
            name='score',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='occasion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='style',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outfitimage',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.title'),
        ),
    ]
