# Generated by Django 5.2.3 on 2025-07-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_color_hex_code_alter_compatibilityrules_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='body_type',
            field=models.CharField(blank=True, choices=[('hourglass', 'Hourglass'), ('pear', 'Pear'), ('apple', 'Apple'), ('rectangle', 'Rectangle'), ('inverted', 'Inverted Triangle'), ('undefined', 'Undefined')], default='undefined', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='outfitimage',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outfit_images', to='myapp.title'),
        ),
    ]
