# Generated by Django 5.2.3 on 2025-08-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_color_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compatibilityrules',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Compatibility Rule', 'verbose_name_plural': 'Compatibility Rules'},
        ),
        migrations.AddField(
            model_name='title',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
