# Generated by Django 5.2.3 on 2025-08-05 09:27

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_compatibilityrules_options_title_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.Title.image_upload_path),
        ),
    ]
