# Generated by Django 5.2.3 on 2025-08-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitimage',
            name='score',
            field=models.FloatField(default=5.0, help_text='User rating score for this outfit (default 5.0)'),
        ),
        migrations.AddField(
            model_name='outfitimage',
            name='vote_count',
            field=models.PositiveBigIntegerField(default=0, help_text='Number of votes for this outfit'),
        ),
    ]
